# Generated by Django 3.2.17 on 2023-03-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_image',
            field=models.ImageField(blank=True, upload_to='promo_images'),
        ),
    ]
