# Generated by Django 3.2.17 on 2023-03-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_promo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='slogan',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
