# Generated by Django 3.2.17 on 2023-04-02 09:51

import django.db.models.deletion
from django.db import migrations, models

import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_productcategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.get_upload_to)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
