# Generated by Django 3.2.17 on 2023-04-02 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_move_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
